name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.x"
      - "feature/*"
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - config/**
      - src/**
      - phpstan*
      - tests/StaticAnalysis/**
  push:
    branches:
      - "*.x"
      - "feature/*"

jobs:
  static-analysis:
    uses: "doctrine/.github/.github/workflows/phpstan.yml@v12.2.0"
